### ISSUE TITLE
html beautify fail to place correctely endind div closing tag

### ISSUE THREAD

**Issue by rachidbch** [zeekay/vim-beautify#1]
hi,
I'm using neovim on ubuntu 14.04.
When I beautify the following code:

``` html
<div class="alert alert-success" role="alert"><strong>Well done!</strong> You successfully read <a href="#" class="alert-link">this important alert message</a>.</div>
```

I end up with following beautified code:

``` html
<div class="alert alert-success" role="alert">
  <strong>Well done!</strong> You successfully read
  <a href="#" class="alert-link">this important alert message</a>.</div>
```

The closing </div> shoud be on a new last line.
When removing the `.` between `</a>` and `</div>`, it works as expected.
Thanks for the good work.

**Comment by zeekay** [comment]
I've had a few weird issues with the underlying library (js-beautify). It might be worth poking the js-beautify maintainers.

**Comment by rachidbch** [comment]
well, I tried to play with the html-beautify cli and its '--extra_liners' option with no success...
Anyway they have 239 open issues ....

**Comment by zeekay** [comment]
You can also try using html-tidy: https://github.com/htacg/tidy-html5. This works fairly well in most cases. Just call `:Beautify tidy` to specify that beautifier instead.
